apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyI0NTgyODMzNDIyMjMuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdzLmNvbSI6eyJ1c2VybmFtZSI6IkFXUyIsInBhc3N3b3JkIjoiQUtJQVdWTTZRM0dIV1hZSkpYNUYiLCJlbWFpbCI6Im5vbmUiLCJhdXRoIjoiUVZkVE9rRkxTVUZYVmswMlVUTkhTRmRZV1VwS1dEVkcifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: your-ecr-secret
type: kubernetes.io/dockerconfigjson
